title: Food Fan
description: A blog about all things food.
url: "https://trickyck.github.io"
baseurl: "/food_fan" # change this to "" if hosted on a custom domain

remote_theme: "mmistakes/so-simple-theme"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

skin: "assets/css/skins/light.css"

logo: "assets/images/logo.png"

author:
  name: trickyck
  avatar: "/assets/images/avatar.png"
  bio: "Fiber-forward food fanatic."

collections:
  pages:
    output: true

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"

# Social
social:
  github: trickyck
  twitter: yourhandle

# Build settings
markdown: kramdown

#Google Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
