title: Food Fan
description: A blog about all things food.
url: "https://trickyck.github.io"
baseurl: "/food_fan" # change this to "" if hosted on a custom domain

remote_theme: "mmistakes/so-simple-theme"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: trickyck
  avatar: "/assets/images/avatar.png"
  bio: "Fiber-forward food fanatic."

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Social
social:
  github: trickyck
  twitter: yourhandle

# Build settings
markdown: kramdown
